---
title: "National Differences in Dissemination and Use of Open Access Literature"
subtitle: (Article)
date: 2022-08-09
author:
  - Marc-André Simard
  - Gita Ghiasi
  - Philippe Mongeon
  - Vincent Larivière
authors:
  - name: Marc-André Simard
    orcid: 0000-0003-3795-0053
    corresponding: true
    email: marc-andre.simard.1@umontreal.ca
    affiliations: 
      - ref: udem
  - name: Gita Ghiasi
    orcid: 0000-0001-8296-6674
    corresponding: false
    affiliations:
      - ref: udem
  - name: Philippe Mongeon
    orcid: 0000-0001-5556-0919
    corresponding: false
    affiliations: 
      - ref: dal
  - name: Vincent Larivière
    orcid: 0000-0002-2733-0689
    corresponding: false
    affiliations: 
      - ref: udem
affiliations:
  - id: dal
    name: Dalhousie University
    address: Halifax, Nova Scotia, Canada
  - id: udem
    name: Université de Montréal
    
categories: 
  - Open Access
  - Countries

bibliography: files/references.bib
csl: files/apa.csl
doi: https://doi.org/10.1371/journal.pone.0272730

code-overflow: wrap
code-tools: 
  source: FALSE
  toggle: TRUE
execute:
  warning: false
  message: false
  error: false
  echo: false
editor_options: 
  chunk_output_type: inline
  
draft: false
---

# Citation

Simard, M.-A., Ghiasi, G., Mongeon, P., & Larivière, V. (2022). National differences in dissemination and use of open access literature. *PLOS ONE*, *17*(8), e0272730. <https://doi.org/10.1371/journal.pone.0272730>

# Abstract

Open Access (OA) dissemination has been gaining a lot of momentum over the last decade, thanks to the implementation of several OA policies by funders and institutions, as well as the development of several new platforms that facilitate the publication of OA content at low or no cost. Studies have shown that nearly half of the contemporary scientific literature could be available online for free. However, few studies have compared the use of OA literature across countries. This study aims to provide a global picture of OA adoption by countries, using two indicators: publications in OA and references made to articles in OA. We find that, on average, low-income countries are publishing and citing OA at the highest rate, while upper middle-income countries and higher-income countries publish and cite OA articles at below world-average rates. These results highlight national differences in OA uptake and suggest that more OA initiatives at the institutional, national, and international levels are needed to support wider adoption of open scholarship.

# Key figures

![Fig 1. Weighted z-score and normalized map of the number of OA publications by country. Red indicates that a country is above the world average, blue indicates it is below the world average. White represents the world average. Contains information from OpenStreetMap and OpenStreetMap Foundation, which is made available under the Open Database License. https://doi.org/10.1371/journal.pone.0272730.g001](images/clipboard-1389803150.png){fig-align="center" width="900"}
